title: Leonel Braginski
url: "https://leobrasileo.github.io"
baseurl: ""

markdown: kramdown
remote_theme: ankitsultana/researcher@gem
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Website template forked from this repo"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: ""
 - name: "cv"
   link: "/cv.pdf"
